### PR TITLE
Code readability

### PR DESCRIPTION
**Pull request by fdhadzh**
Make code more readable

### CODE REVIEW

**Comment by mialinx** [comment]
This PR affects public interface, such as error constants names  ( ErrInvalidUuid / ErrInvalidUUID ), Schema structure fields ( FieldsById / FieldsByID ).  It may break backward compatibility.

**Comment by funny-falcon** [comment]
why don't you like requestId ? It is valid camel case, and requestID is not.
So I against all changes Id => ID except Uuid => UUID.

s/Errorf/Error/ is ok for me.
And s/resp_bytes/respBytes/.
And struct initialization in NewRequest.
And sort of imports.
And some indentation fixes.

All rest changes are meaningless for me.

**Comment by mialinx** [comment]
Indentation an sort of imports problems should be solved by gofmt.

**Comment by funny-falcon** [comment]
> Indentation an sort of imports problems should be solved by gofmt.

Agree. We should not forget run it ;-)

**Comment by mialinx** [comment]
.gitignore was changed manually
gofmt applied to all files
some of golint recommendation were applied (excluding ID/Id issues and comments)

**Comment by rybakit** [comment]
> .gitignore was changed manually

IMHO, such kind of changes should not be a part of the repository, but go to the global .gitingore file on the developer's environment, otherwise you may end up with a mess of ignore rules for each and every IDE/editor available in the wild ;)

**Pull request closed without merging**
