### PR TITLE
Added the ability to work with the tarantool via unix socket

### PR DESCRIPTION
**Pull request by monoflash**

### CODE REVIEW

**Comment by funny-falcon** [comment]
https://tarantool.org/en/doc/reference/configuration/index.html#index-uri
https://tarantool.org/en/doc/book/administration.html#administration-admin-ports
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax

suggested algorithm:
```go
if address[0:5] == "unix:" {
    network = "unix"
    address = address[5:]
} else if address[0:4] == "tcp:" {
    network = "tcp"
    address = address[4:]
} else if address[0] == '/' || address[0] == '.' {
    network = "unix"
} else {
    network = "tcp"
}
```

Either you add it to your commits, or I will add it after merge.
Choose.

**Comment by monoflash** [comment]
Better you add this correction from yourself.

**Comment by funny-falcon** [comment]
No problem. prefix will be 'unix:' . I'll merge it tommorow.

**Comment by funny-falcon** [comment]
Thank you for contribution :-) hope this will be first among many.

**Comment by funny-falcon** [comment]
Well, I wasn't exactly right about `unix/:`. It is really ugly, but looks like it was adopted by tarantool :-(
So, I decided to keep it.

**Pull request merged**
