### PR TITLE
ci: use merge commit for pull_request_target

### PR DESCRIPTION
**Pull request by oleg-jukovec**
It would be more correct to use a merge request commit instead of original commit for pull_request_target.

### CODE REVIEW

**Review by DifferentialOrange — COMMENTED** [review]
To be honest, I don't get it without some additional context. Does merge commits are built with GitHub for each Pull request disregarding repo settings (we don't use merge commits anywhere)? What can go wrong in case of current solution?

**Comment by oleg-jukovec** [comment]
> To be honest, I don't get it without some additional context. Do merge commits are built with GitHub for each Pull request disregarding repo settings (we don't use merge commits anywhere)? What can go wrong in case of current solution?

1. The idea was to skip tests with Tarantool EE for outside pull requests.
2. A user with write access should mark the pull request with lable `full-ci` to start tests with Tarantool EE.

It is necessary in order to keep repository secrets safe. `pull_request_target` event on Github Actions has access to the repository secrets, but it works in the context of a base commit.

Therefore, additional actions are needed to checkout a right commit from a outside pull request.

The patch changes the commit from the original one (outside branch + outside commit) to a pull request commit (`merge` commit).

**Comment by DifferentialOrange** [comment]
> > To be honest, I don't get it without some additional context. Do merge commits are built with GitHub for each Pull request disregarding repo settings (we don't use merge commits anywhere)? What can go wrong in case of current solution?
> 
> The idea was to skip tests with Tarantool EE for outside pull requests. A user with write access to the repository should mark the pull request with lable `full-ci` to start tests with Tarantool EE.
> 
> It is necessary in order to keep repository secrets safe. `pull_request_target` event on Github Actions has access to the repository secrets, but it works in the context of a base commit.
> 
> Therefore, additional actions are needed to checkout a right commit from the outside pull request.
> 
> The patch changes the commit for checkout from the original one (outside branch + outside commit) to a pull request commit (`merge` commit) for `pull_request_target`.
> 
> https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

So... is this a protection of getting CI run approve for some commit and then adding some commits below it? (Which also sounds impossible)

**Comment by oleg-jukovec** [comment]
> So... is this a protection of getting CI run approve for some commit and then adding some commits below it? (Which also sounds impossible)

If we are talking about the fix, then there is a difference between:

1. Run CI on last commit of branch X, repo B.
2. Run CI on merge-pull request commit.

The fix changes the case from 1. to 2. It looks more correct because when updating the base branch it updates merge-pull request commit.

**Review by DifferentialOrange — APPROVED** [review]

**Review by better0fdead — APPROVED** [review]

**Pull request merged**
