### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by oleg-jukovec**
## Overview
    
This release adds a number of features. Also it significantly improves testing, CI and documentation.
    
## Breaking changes

There are no breaking changes in the release.
    
## New features
    
* Support UUID type in msgpack (#90).
* queue-utube handling (#85).
* Master discovery (#113).
* SQL support (#62).

## Bugfixes

* Reset buffer if its average use size smaller than quater of capacity (#95).

## Testing

* Coveralls support (#149).
* Reusable testing workflow (integration testing with latest Tarantool) (#112).
* Simple CI based on GitHub actions (#114).
* Handle everything with `go test` (#115).
* Fix queue tests (#107).
* Make test case consistent with comments (#105).

## Other

* Go modules support (#91).
* Update API documentation: comments and examples (#123).

### CODE REVIEW

**Comment by oleg-jukovec** [comment]
[From the wiki page](https://github.com/tarantool/go-tarantool/wiki/How-to-release):

> Rename 'Unreleased' version to the next version number with release date and add a new empty section 'Unreleased' with empty Added, Changed, Removed subsections.

But I left empty `Added`, `Changed`, `Fixed` subsections. Because it was in the CHANGELOG.md before and [it is now at crud](https://github.com/tarantool/crud/blob/master/CHANGELOG.md). Should I change the CHANGELOG.md or the wiki page?

**Comment by Totktonada** [comment]
I usually add build/testing/CI/code health changes into its own section(s) ([example](https://github.com/tarantool/tarantool-python/releases/tag/0.8.0)), because it is mostly for developers. I look at the release notes mainly in reflection of the 'what is new from a user point of view' -- this information should be presented at beginning of the document. But we can add 'what else nice occurs here' at bottom.

**Comment by Totktonada** [comment]
> Should I change the CHANGELOG.md or the wiki page?

I agree. Let's modify the instruction of the wiki.

**Review by Totktonada — APPROVED** [review]

**Comment by oleg-jukovec** [comment]
> I usually add build/testing/CI/code health changes into its own section(s) ([example](https://github.com/tarantool/tarantool-python/releases/tag/0.8.0))

I've added 'Testing' and 'Other' sections into the commit message, into the pull request message and into the draft release request. I will synchronize [the wiki page](https://github.com/tarantool/go-tarantool/wiki/How-to-release) with the changes after the release.

**Comment by DifferentialOrange** [comment]
> Reusable testing workflow (integration testing with latest Tarantool) (https://github.com/tarantool/go-tarantool/issues/123).

It looks like wrong issue is linked.

**Review by DifferentialOrange — APPROVED** [review]
LGTM after resolving a comment above.

How Golang modules are released? Is repo tag enough?

**Comment by oleg-jukovec** [comment]
> > Reusable testing workflow (integration testing with latest Tarantool) (#123).
> 
> It looks like wrong issue is linked.

Thank you. You are right. It's #112.
I've updated CHANGELOG.md, the commit message, the pull request message, the draft pull request.

**Review by AnaNek — APPROVED** [review]

**Pull request merged**
