### PR TITLE
Update vmihailenco/msgpack to v5

### PR DESCRIPTION
**Pull request by oleggator**
## Breaking change
Now msgpack encoded integers decodes to corresponding Golang integer type.
It's the behaviour of the new version of vmihailenco/msgpack library.

**For example**:
before: int8 msgpack encoded integer decodes to int64 Golang variable
now: int8 msgpack encoded integer decodes to int8 Golang variable

### CODE REVIEW

**Comment by funny-falcon** [comment]
First, it is breaking change, therefore it could not be merged before V2.
Second, I HATE THIS CHANGE in vmichailenco/msgpack. It is most stupid thing he could make with his library, and he did it indeed. This main thing I don't want to mess with newer versions of vmichailenco/msgpack and wish to replace it with something different.

**Comment by FZambia** [comment]
`decoder.UseLooseInterfaceDecoding(true)` should help I suppose?

**Comment by funny-falcon** [comment]
@FZambia hmm... looks promising.

**Comment by oleggator** [comment]
Good idea.
But the behaviour still different from v2. [In v5 fixed numbers decodes to int64](https://github.com/vmihailenco/msgpack/blob/v5/decode.go#L453), but [in v2 they decodes to uint64](https://github.com/vmihailenco/msgpack/blob/v2.9.1/decode.go#L250).

**Comment by FZambia** [comment]
Yeah, this is still a breaking change... But maybe this can help staying with `vmihailenco/msgpack` in `go-tarantool` next major release.

**Comment by ernado** [comment]
We need msgpack.RawMessage support and going to maintain internal fork until this is merged.

**Comment by Totktonada** [comment]
This work is continued in PR #174.

**Pull request closed without merging**
